version: '3.9'

services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rtpas
      MYSQL_DATABASE: mariadb
      MYSQL_USER: dbusr
      MYSQL_PASSWORD: dbpas

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dbusr
      WORDPRESS_DB_PASSWORD: dbpas
      WORDPRESS_DB_NAME: mariadb
    volumes:
      - ./wp_data:/var/www/html
volumes:
  db_data:
  wp_data:
