version: '3'

services:

  db:
    image: 'mysql:5.7'
    container_name: mysql
    volumes:
      - ./mount/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rtpas
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: adpas
    networks:
      - wpnet

  wordpress:
    image: 'wordpress:latest'
    container_name: wordpress
    depends_on:
      - db
    restart: always
    volumes:
      - ./mount/wp/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: adpas
      WORDPRESS_DB_NAME: mysql
    ports:
      - '8000:80'
    networks:
      - wpnet

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rtpas
    networks:
      - wpnet

  manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    container_name: manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./mount/prox_manager/data:/data
      - ./mount/prox_manager/letsencrypt:/etc/letsencrypt
    networks:
      - wpnet
    depends_on:
      - db
volumes:
  mysql:
  prox_manager:
networks:
  wpnet:
