version: '3'

services:

  db:
    image: 'mysql:5.7'
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rtpas
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: adpas
    networks:
      - wpnet

  wordpress:
    image: 'wordpress:latest'
    container_name: wordpress
    depends_on:
      - db
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: adpas
      WORDPRESS_DB_NAME: mysql
    networks:
      - wpnet

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rtpas
    networks:
      - wpnet

volumes:
  db_data:
  wp_data:
networks:
  wpnet:
